### ISSUE TITLE
300多个城市为什么没有沧州?

### ISSUE THREAD

**Issue by chldong** [pyecharts/echarts-china-cities-js#1]
难道是沧州要取消么?:)

**Comment by chfw** [comment]
哈哈 您挺幽默的。我查看一下 再具体回复

**Comment by chfw** [comment]
是我下载的bot给漏掉了。现在情况是，高德下载被叫停了，暂时无法解决。你有沧州的geojson吗？

**Comment by chfw** [comment]
2017年再没有，在2018年我就用鼠标手工画。

**Comment by chfw** [comment]
https://zh.wikipedia.org/wiki/%E6%B2%A7%E5%B7%9E%E5%B8%82#%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%88%92

**Comment by chfw** [comment]
谢谢来自@AggerChen的帮助：
<img width="273" alt="screen shot 2017-12-29 at 23 46 07" src="https://user-images.githubusercontent.com/4280312/34449691-0bb7f992-ecf3-11e7-892e-6ced2e135426.png">
